# config.ini for preprocess
# spatial_arrangement: G:lcd type,R&B:diamond type
# location_mapping: 0:auto calculation n:set n as mapping number
# location_rows(cols)_tolerate_pixels: n: n pixels dark point or bad pixels tolerate for location
# position: panel left-top corner in image position, left-top:1 right-top:2 right-bottom:3 left-bottom:4
# camera_index: image processing index
# save_location_map: check if location is right
# de_moire:  eg(1,0.05,2) 1: on or off(0 or 1), 0.05: moire selection range(0-1), 2: demoire strength(1/2/3...)

[Database]
data_path = D:\dc\python\vlm\raw
location_color = R,G,B
gray_color = W
position = 4
pattern_type = tif
location_interval = 4

location_mapping = 0
brightness_mapping = 0
location_rows_tolerate_pixels = 3
location_cols_tolerate_pixels = 6

camera_index = R251,G251,B251,W127
camera_index_exp = 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
camera_index_gain = 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

[Tool]
sandy_quantization = 0
moire_quantization = 0
csv_demoire = 0,0.04,4

[Panel]
panel_res_rows = 2392
panel_res_cols = 1080

[AOI]
aoi = 0
model_type = pt
model_path = F:\DATA\CODE\PYTHON\IP_2\IP_2\weights\best.pt

[Preprocess]
ffc = 0

[Process]
hole_corner_filling = 0
de_moire = 0,0.05,2

[Saving]
save_csv = 0
save_roi = 1
save_mat = 0
save_location_map = 1