# config.ini for preprocess
# spatial_arrangement: G:lcd type,R&B:diamond type
# location_mapping: 0:auto calculation n:set n as mapping number
# location_rows(cols)_tolerate_pixels: n: n pixels dark point or bad pixels tolerate for location
# position: panel left-top corner in image position, left-top:1 right-top:2 right-bottom:3 left-bottom:4
# camera_index: image processing index
# save_location_map: check if location is right
# ffc: 1: exist calibration data(unavailable)  2: physics model for ffc(availavle)
# de_moire:  eg(1,0.05,2) 1: on or off(0 or 1), 0.05: moire selection range(0-1), 2: demoire strength(1/2/3...)
# curved_corr: eg(28,0.8,0.92) 28:curved pixels nums, 0.8:28 pixels * 0.8, make it darker or brighter, 0.92: noticeable area adjust, if first position set as 0, curved_corr off
# curved_color_dev: eg(10,1.1,1.2,0.9), curved 10 pixels area, R * 1.1, G * 1.2, B * 0.9
curved_corr_2: eg(28,14,0.7,0.8,0.9,6): 28-14pixels areas, 0.7R,0.8G,0.9B, blur smooth sigma 6

[Database]
data_path = C:\Users\84257\Desktop\temp
location_color = W
gray_color = W
position = 4
pattern_type = csv
location_interval = 0

location_mapping = 6,5,6
brightness_mapping = 7,5,7
location_rows_tolerate_pixels = 5
location_cols_tolerate_pixels = 8

camera_index = R240
camera_index_exp = 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
camera_index_gain = 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

[Tool]
sandy_quantization = 1
moire_quantization = 0
csv_demoire = 0,0.04,4

[Panel]
panel_res_rows = 2768
panel_res_cols = 1272

[AOI]
aoi = 0
model_type = pt
model_path = F:\DATA\CODE\PYTHON\IP_2\IP_2\weights\best.pt

[Preprocess]
ffc = 0

[Process]
hole_corner_filling = 1
de_moire = 0,0.05,2
curved_corr = 0,0.95,0.2
curved_corr_2 = 28,14,0.7,0.8,0.9,1
curved_color_dev = 14,1.8,0,0
curved_color_dev_2 = 22,1.8,0,0

[Saving]
save_csv = 1
save_roi = 0
save_mat = 0
save_location_map = 1